-- =====================================================
-- SISTEMA PATITAS SEGURAS
-- =====================================================

SET client_encoding = 'UTF8';

-- =====================================================
-- ENUMS
-- =====================================================
CREATE TYPE sexo_enum AS ENUM ('macho', 'hembra');
CREATE TYPE tamaño_enum AS ENUM ('pequeño', 'mediano', 'grande');
CREATE TYPE tipo_parasito_enum AS ENUM ('interno', 'externo', 'ambos');

-- =====================================================
-- SEGURIDAD Y USUARIOS
-- =====================================================
CREATE TABLE roles (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nombre_rol VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE provincias (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(50) NOT NULL UNIQUE,

    PRIMARY KEY (id)
);

CREATE TABLE comunas_municipios (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_provincia INT NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    CONSTRAINT uq_comuna_municipio UNIQUE (id_provincia, nombre),

    PRIMARY KEY (id)
);

CREATE TABLE localidades (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_comuna_municipio INT NOT NULL,
    nombre_localidad VARCHAR(50) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_localidad UNIQUE (id_comuna_municipio, nombre_localidad),

    PRIMARY KEY (id)
);

CREATE TABLE barrios_zonas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_localidad INT NOT NULL,
    nombre_barrio VARCHAR(50) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_barrio_zona UNIQUE (id_localidad, nombre_barrio),

    PRIMARY KEY (id)
);

CREATE TABLE tipos_vivienda (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nombre_tipo VARCHAR(50) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE domicilios_detalles (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_tipo_vivienda INT NOT NULL,
    id_barrio_zona INT NOT NULL,
    calle VARCHAR(50),
    altura VARCHAR(10),
    piso VARCHAR(10),
    departamento VARCHAR(10),
    ruta_nombre VARCHAR(50),
    kilometro NUMERIC(7,2),
    entre_calle_1 VARCHAR(50),
    entre_calle_2 VARCHAR(50),
    indicadores_referencia VARCHAR(150),
    CONSTRAINT chk_domicilio_kilometro CHECK (kilometro IS NULL OR kilometro >= 0),

    PRIMARY KEY (id)
);

CREATE TABLE usuarios_domicilios (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_domicilio_detalle INT NOT NULL,
    codigo_postal VARCHAR(10),

    PRIMARY KEY (id)
);

CREATE TABLE usuarios (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_rol INT NOT NULL,
    id_domicilio INT,
    nombre VARCHAR(30) NOT NULL,
    apellido VARCHAR(30) NOT NULL,
    password VARCHAR(255) NOT NULL,
    fecha_nacimiento DATE,
    fecha_alta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_usuario_fecha_nacimiento
        CHECK (fecha_nacimiento IS NULL OR fecha_nacimiento <= CURRENT_DATE),

    PRIMARY KEY (id)
);

CREATE TABLE tipos_contacto (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    descripcion VARCHAR(50) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE contactos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_tipo_contacto INT NOT NULL,
    id_usuario INT NOT NULL,
    valor VARCHAR(100) NOT NULL,
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,
    observaciones TEXT,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);


-- =====================================================
-- MASCOTAS Y SALUD
-- =====================================================
CREATE TABLE especies (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nombre_especie VARCHAR(20) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE razas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_especie INT NOT NULL,
    nombre_raza VARCHAR(50) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_raza_nombre UNIQUE (id_especie, nombre_raza),
    CONSTRAINT uq_raza_especie_id UNIQUE (id, id_especie),

    PRIMARY KEY (id)
);

CREATE TABLE mascotas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_especie INT NOT NULL,
    id_raza INT NOT NULL,
    nombre VARCHAR(30) NOT NULL,
    sexo sexo_enum NOT NULL,
    tamaño tamaño_enum NOT NULL,
    fecha_nacimiento_estimada DATE,
    historial TEXT,
    foto_url VARCHAR(500),
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT chk_mascota_fecha_nacimiento
        CHECK (fecha_nacimiento_estimada IS NULL OR fecha_nacimiento_estimada <= CURRENT_DATE),

    PRIMARY KEY (id)
);

CREATE TABLE fichas_medicas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_mascota INT NOT NULL UNIQUE,
    observaciones TEXT,
    fecha_actualizacion DATE,

    PRIMARY KEY (id)
);

CREATE TABLE controles_medicos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_ficha_medica INT NOT NULL,
    fecha_control DATE NOT NULL,
    peso NUMERIC(6,2),
    observaciones TEXT,
    CONSTRAINT chk_control_peso CHECK (peso IS NULL OR peso > 0),

    PRIMARY KEY (id)
);

CREATE TABLE castraciones (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_ficha_medica INT NOT NULL UNIQUE,
    fecha_castracion DATE,
    observaciones TEXT,

    PRIMARY KEY (id)
);

CREATE TABLE tipos_vacunas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nombre_vacuna VARCHAR(50) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE vacunas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_ficha_medica INT NOT NULL,
    id_tipo_vacuna INT NOT NULL,
    numero_dosis INT NOT NULL,
    fecha_aplicacion DATE NOT NULL,
    proxima_dosis DATE,
    observaciones TEXT,
    CONSTRAINT chk_vacuna_numero_dosis CHECK (numero_dosis > 0),
    CONSTRAINT chk_vacuna_proxima_dosis
        CHECK (proxima_dosis IS NULL OR proxima_dosis >= fecha_aplicacion),

    PRIMARY KEY (id)
);

CREATE TABLE tipos_productos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nombre_tipo VARCHAR(30) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE desparasitaciones (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_ficha_medica INT NOT NULL,
    id_tipo_producto INT NOT NULL,
    tipo_parasito tipo_parasito_enum NOT NULL,
    fecha_aplicacion DATE NOT NULL,
    proxima_dosis DATE,
    observaciones TEXT,
    CONSTRAINT chk_desparasitacion_proxima_dosis
        CHECK (proxima_dosis IS NULL OR proxima_dosis >= fecha_aplicacion),

    PRIMARY KEY (id)
);

-- =====================================================
-- SOLICITUDES
-- =====================================================
CREATE TABLE tipos_movimientos_solicitudes (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nombre_movimiento VARCHAR(30) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE tipos_solicitudes (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_tipo_movimiento INT NOT NULL,
    nombre_tipo VARCHAR(30) NOT NULL,
    estado BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_tipo_solicitud UNIQUE (id_tipo_movimiento, nombre_tipo),

    PRIMARY KEY (id)
);

CREATE TABLE estados_solicitudes (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nombre_estado VARCHAR(30) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE solicitudes (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario INT NOT NULL,
    id_mascota INT NOT NULL,
    id_tipo_solicitud INT NOT NULL,
    id_estado_solicitud INT NOT NULL,
    fecha_solicitud DATE NOT NULL DEFAULT CURRENT_DATE,

    PRIMARY KEY (id)
);

-- =====================================================
-- ADOPCIÓN Y HOGAR DE TRÁNSITO
-- =====================================================
CREATE TABLE tipos_vivienda_formulario (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    descripcion VARCHAR(50) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE condiciones_vivienda (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    descripcion VARCHAR(50) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE tipos_patio (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    descripcion VARCHAR(50) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE destinos_mascotas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    descripcion VARCHAR(100) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE tipos_mascotas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    descripcion VARCHAR(30) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE categorias_mascotas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    descripcion VARCHAR(50) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE condiciones_especiales (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    descripcion VARCHAR(50) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE compromisos_adopcion (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    descripcion VARCHAR(150) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE formularios_adopcion (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_solicitud INT NOT NULL UNIQUE,
    id_tipo_vivienda INT NOT NULL,
    id_condicion_vivienda INT NOT NULL,
    id_tipo_patio INT NOT NULL,
    metros_cuadrados_patio NUMERIC(7,2),
    id_destino_mascota INT NOT NULL,
    cantidad_integrantes INT NOT NULL,
    hay_ninos BOOLEAN NOT NULL,
    horas_solo INT,
    acepta_seguimiento BOOLEAN NOT NULL,
    responsable_principal VARCHAR(60) NOT NULL,
    motivo_adopcion VARCHAR(250),
    observaciones TEXT,
    CONSTRAINT chk_adopcion_metros_patio
        CHECK (metros_cuadrados_patio IS NULL OR metros_cuadrados_patio >= 0),
    CONSTRAINT chk_adopcion_integrantes CHECK (cantidad_integrantes > 0),
    CONSTRAINT chk_adopcion_horas_solo
        CHECK (horas_solo IS NULL OR horas_solo BETWEEN 0 AND 24),

    PRIMARY KEY (id)
);

CREATE TABLE formulario_adopcion_compromisos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_formulario_adopcion INT NOT NULL,
    id_compromiso_adopcion INT NOT NULL,
    CONSTRAINT uq_formulario_adopcion_compromiso
        UNIQUE (id_formulario_adopcion, id_compromiso_adopcion),

    PRIMARY KEY (id)
);

CREATE TABLE formulario_adopcion_mascotas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_tipo_mascota INT NOT NULL,
    id_formulario_adopcion INT NOT NULL,
    cantidad INT NOT NULL,
    cantidad_esterilizadas INT NOT NULL DEFAULT 0,
    CONSTRAINT uq_formulario_adopcion_tipo_mascota
        UNIQUE (id_formulario_adopcion, id_tipo_mascota),
    CONSTRAINT chk_adopcion_mascotas_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_adopcion_mascotas_esterilizadas
        CHECK (cantidad_esterilizadas >= 0 AND cantidad_esterilizadas <= cantidad),

    PRIMARY KEY (id)
);

CREATE TABLE formulario_adopcion_categorias (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_categoria INT NOT NULL,
    id_formulario_adopcion INT NOT NULL,
    CONSTRAINT uq_formulario_adopcion_categoria
        UNIQUE (id_formulario_adopcion, id_categoria),

    PRIMARY KEY (id)
);

CREATE TABLE formulario_adopcion_condiciones (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_condicion_especial INT NOT NULL,
    id_formulario_adopcion INT NOT NULL,
    CONSTRAINT uq_formulario_adopcion_condicion
        UNIQUE (id_formulario_adopcion, id_condicion_especial),

    PRIMARY KEY (id)
);

CREATE TABLE formulario_hogar_transito (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_solicitud INT NOT NULL UNIQUE,
    id_tipo_vivienda INT NOT NULL,
    id_condicion_vivienda INT NOT NULL,
    id_tipo_patio INT NOT NULL,
    metros_cuadrados_patio NUMERIC(7,2),
    cantidad_integrantes INT NOT NULL,
    hay_ninos BOOLEAN NOT NULL,
    horas_solo INT,
    cantidad_maxima_mascota INT NOT NULL,
    puede_administrar_medicacion BOOLEAN NOT NULL,
    observaciones TEXT,
    CONSTRAINT chk_transito_metros_patio
        CHECK (metros_cuadrados_patio IS NULL OR metros_cuadrados_patio >= 0),
    CONSTRAINT chk_transito_integrantes CHECK (cantidad_integrantes > 0),
    CONSTRAINT chk_transito_horas_solo
        CHECK (horas_solo IS NULL OR horas_solo BETWEEN 0 AND 24),
    CONSTRAINT chk_transito_cantidad_maxima CHECK (cantidad_maxima_mascota > 0),

    PRIMARY KEY (id)
);

CREATE TABLE formulario_transito_mascotas (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_tipo_mascota INT NOT NULL,
    id_formulario_transito INT NOT NULL,
    cantidad INT NOT NULL,
    cantidad_esterilizadas INT NOT NULL DEFAULT 0,
    CONSTRAINT uq_formulario_transito_tipo_mascota
        UNIQUE (id_formulario_transito, id_tipo_mascota),
    CONSTRAINT chk_transito_mascotas_cantidad CHECK (cantidad > 0),
    CONSTRAINT chk_transito_mascotas_esterilizadas
        CHECK (cantidad_esterilizadas >= 0 AND cantidad_esterilizadas <= cantidad),

    PRIMARY KEY (id)
);

CREATE TABLE formulario_transito_categorias (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_categoria INT NOT NULL,
    id_formulario_transito INT NOT NULL,
    CONSTRAINT uq_formulario_transito_categoria
        UNIQUE (id_formulario_transito, id_categoria),

    PRIMARY KEY (id)
);

CREATE TABLE formulario_transito_condiciones (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_condicion_especial INT NOT NULL,
    id_formulario_transito INT NOT NULL,
    CONSTRAINT uq_formulario_transito_condicion
        UNIQUE (id_formulario_transito, id_condicion_especial),

    PRIMARY KEY (id)
);

-- =====================================================
-- MOVIMIENTOS / DONACIONES
-- =====================================================
CREATE TABLE tipos_movimientos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nombre_movimiento VARCHAR(50) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE tipos_aportes (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nombre_aporte VARCHAR(50) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE frecuencia_aportes (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nombre_frecuencia_aporte VARCHAR(50) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE metodos_pago (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    nombre_metodo VARCHAR(50) NOT NULL UNIQUE,
    estado BOOLEAN NOT NULL DEFAULT TRUE,

    PRIMARY KEY (id)
);

CREATE TABLE movimientos (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario INT NOT NULL,
    id_tipo_movimiento INT NOT NULL,
    id_tipo_aporte INT NOT NULL,
    id_metodo_pago INT,
    id_frecuencia_aporte INT,
    fecha DATE NOT NULL DEFAULT CURRENT_DATE,
    monto NUMERIC(12,2),
    descripcion TEXT,
    CONSTRAINT chk_movimiento_monto CHECK (monto IS NULL OR monto > 0),

    PRIMARY KEY (id)
);

-- =====================================================
-- AUDITORÍAS
-- =====================================================
CREATE TABLE auditorias (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario INT,
    nombre_tabla VARCHAR(50) NOT NULL,
    accion VARCHAR(20) NOT NULL,
    fecha_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valores_anteriores JSONB,
    valores_nuevos JSONB,
    ip_origen VARCHAR(45),
    CONSTRAINT chk_auditoria_accion
        CHECK (accion IN ('INSERT', 'UPDATE', 'DELETE')),

    PRIMARY KEY (id)
);

-- =====================================================
-- RELACIONES / FOREIGN KEYS
-- =====================================================
ALTER TABLE comunas_municipios
    ADD CONSTRAINT fk_comuna_municipio_provincia FOREIGN KEY (id_provincia) REFERENCES provincias(id);

ALTER TABLE localidades
    ADD CONSTRAINT fk_localidad_comuna_municipio FOREIGN KEY (id_comuna_municipio) REFERENCES comunas_municipios(id);

ALTER TABLE barrios_zonas
    ADD CONSTRAINT fk_barrio_zona_localidad FOREIGN KEY (id_localidad) REFERENCES localidades(id);

ALTER TABLE domicilios_detalles
    ADD CONSTRAINT fk_domicilio_tipo_vivienda FOREIGN KEY (id_tipo_vivienda) REFERENCES tipos_vivienda(id);

ALTER TABLE domicilios_detalles
    ADD CONSTRAINT fk_domicilio_barrio_zona FOREIGN KEY (id_barrio_zona) REFERENCES barrios_zonas(id);

ALTER TABLE usuarios_domicilios
    ADD CONSTRAINT fk_usuario_domicilio_detalle FOREIGN KEY (id_domicilio_detalle) REFERENCES domicilios_detalles(id);

ALTER TABLE usuarios
    ADD CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol) REFERENCES roles(id);

ALTER TABLE usuarios
    ADD CONSTRAINT fk_usuario_domicilio FOREIGN KEY (id_domicilio) REFERENCES usuarios_domicilios(id);

ALTER TABLE contactos
    ADD CONSTRAINT fk_contacto_tipo FOREIGN KEY (id_tipo_contacto) REFERENCES tipos_contacto(id);

ALTER TABLE contactos
    ADD CONSTRAINT fk_contacto_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id);

ALTER TABLE razas
    ADD CONSTRAINT fk_raza_especie FOREIGN KEY (id_especie) REFERENCES especies(id);

ALTER TABLE mascotas
    ADD CONSTRAINT fk_mascota_especie FOREIGN KEY (id_especie) REFERENCES especies(id);

ALTER TABLE mascotas
    ADD CONSTRAINT fk_mascota_raza_especie FOREIGN KEY (id_raza, id_especie) REFERENCES razas(id, id_especie);

ALTER TABLE fichas_medicas
    ADD CONSTRAINT fk_ficha_medica_mascota FOREIGN KEY (id_mascota) REFERENCES mascotas(id);

ALTER TABLE controles_medicos
    ADD CONSTRAINT fk_control_ficha_medica FOREIGN KEY (id_ficha_medica) REFERENCES fichas_medicas(id);

ALTER TABLE castraciones
    ADD CONSTRAINT fk_castracion_ficha_medica FOREIGN KEY (id_ficha_medica) REFERENCES fichas_medicas(id);

ALTER TABLE vacunas
    ADD CONSTRAINT fk_vacuna_ficha_medica FOREIGN KEY (id_ficha_medica) REFERENCES fichas_medicas(id);

ALTER TABLE vacunas
    ADD CONSTRAINT fk_vacuna_tipo FOREIGN KEY (id_tipo_vacuna) REFERENCES tipos_vacunas(id);

ALTER TABLE desparasitaciones
    ADD CONSTRAINT fk_desparasitacion_ficha_medica FOREIGN KEY (id_ficha_medica) REFERENCES fichas_medicas(id);

ALTER TABLE desparasitaciones
    ADD CONSTRAINT fk_desparasitacion_producto FOREIGN KEY (id_tipo_producto) REFERENCES tipos_productos(id);

ALTER TABLE tipos_solicitudes
    ADD CONSTRAINT fk_tipo_solicitud_movimiento FOREIGN KEY (id_tipo_movimiento) REFERENCES tipos_movimientos_solicitudes(id);

ALTER TABLE solicitudes
    ADD CONSTRAINT fk_solicitud_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id);

ALTER TABLE solicitudes
    ADD CONSTRAINT fk_solicitud_mascota FOREIGN KEY (id_mascota) REFERENCES mascotas(id);

ALTER TABLE solicitudes
    ADD CONSTRAINT fk_solicitud_tipo FOREIGN KEY (id_tipo_solicitud) REFERENCES tipos_solicitudes(id);

ALTER TABLE solicitudes
    ADD CONSTRAINT fk_solicitud_estado FOREIGN KEY (id_estado_solicitud) REFERENCES estados_solicitudes(id);

ALTER TABLE formularios_adopcion
    ADD CONSTRAINT fk_formulario_adopcion_solicitud FOREIGN KEY (id_solicitud) REFERENCES solicitudes(id);

ALTER TABLE formularios_adopcion
    ADD CONSTRAINT fk_formulario_adopcion_tipo_vivienda FOREIGN KEY (id_tipo_vivienda) REFERENCES tipos_vivienda_formulario(id);

ALTER TABLE formularios_adopcion
    ADD CONSTRAINT fk_formulario_adopcion_condicion_vivienda FOREIGN KEY (id_condicion_vivienda) REFERENCES condiciones_vivienda(id);

ALTER TABLE formularios_adopcion
    ADD CONSTRAINT fk_formulario_adopcion_tipo_patio FOREIGN KEY (id_tipo_patio) REFERENCES tipos_patio(id);

ALTER TABLE formularios_adopcion
    ADD CONSTRAINT fk_formulario_adopcion_destino_mascota FOREIGN KEY (id_destino_mascota) REFERENCES destinos_mascotas(id);

ALTER TABLE formulario_adopcion_compromisos
    ADD CONSTRAINT fk_formulario_adopcion_compromiso_formulario FOREIGN KEY (id_formulario_adopcion) REFERENCES formularios_adopcion(id);

ALTER TABLE formulario_adopcion_compromisos
    ADD CONSTRAINT fk_formulario_adopcion_compromiso_catalogo FOREIGN KEY (id_compromiso_adopcion) REFERENCES compromisos_adopcion(id);

ALTER TABLE formulario_adopcion_mascotas
    ADD CONSTRAINT fk_adopcion_mascotas_tipo FOREIGN KEY (id_tipo_mascota) REFERENCES tipos_mascotas(id);

ALTER TABLE formulario_adopcion_mascotas
    ADD CONSTRAINT fk_adopcion_mascotas_formulario FOREIGN KEY (id_formulario_adopcion) REFERENCES formularios_adopcion(id);

ALTER TABLE formulario_adopcion_categorias
    ADD CONSTRAINT fk_adopcion_categoria FOREIGN KEY (id_categoria) REFERENCES categorias_mascotas(id);

ALTER TABLE formulario_adopcion_categorias
    ADD CONSTRAINT fk_adopcion_categoria_formulario FOREIGN KEY (id_formulario_adopcion) REFERENCES formularios_adopcion(id);

ALTER TABLE formulario_adopcion_condiciones
    ADD CONSTRAINT fk_adopcion_condicion_especial FOREIGN KEY (id_condicion_especial) REFERENCES condiciones_especiales(id);

ALTER TABLE formulario_adopcion_condiciones
    ADD CONSTRAINT fk_adopcion_condicion_formulario FOREIGN KEY (id_formulario_adopcion) REFERENCES formularios_adopcion(id);

ALTER TABLE formulario_hogar_transito
    ADD CONSTRAINT fk_formulario_transito_solicitud FOREIGN KEY (id_solicitud) REFERENCES solicitudes(id);

ALTER TABLE formulario_hogar_transito
    ADD CONSTRAINT fk_formulario_transito_tipo_vivienda FOREIGN KEY (id_tipo_vivienda) REFERENCES tipos_vivienda_formulario(id);

ALTER TABLE formulario_hogar_transito
    ADD CONSTRAINT fk_formulario_transito_condicion_vivienda FOREIGN KEY (id_condicion_vivienda) REFERENCES condiciones_vivienda(id);

ALTER TABLE formulario_hogar_transito
    ADD CONSTRAINT fk_formulario_transito_tipo_patio FOREIGN KEY (id_tipo_patio) REFERENCES tipos_patio(id);

ALTER TABLE formulario_transito_mascotas
    ADD CONSTRAINT fk_transito_mascotas_tipo FOREIGN KEY (id_tipo_mascota) REFERENCES tipos_mascotas(id);

ALTER TABLE formulario_transito_mascotas
    ADD CONSTRAINT fk_transito_mascotas_formulario FOREIGN KEY (id_formulario_transito) REFERENCES formulario_hogar_transito(id);

ALTER TABLE formulario_transito_categorias
    ADD CONSTRAINT fk_transito_categoria FOREIGN KEY (id_categoria) REFERENCES categorias_mascotas(id);

ALTER TABLE formulario_transito_categorias
    ADD CONSTRAINT fk_transito_categoria_formulario FOREIGN KEY (id_formulario_transito) REFERENCES formulario_hogar_transito(id);

ALTER TABLE formulario_transito_condiciones
    ADD CONSTRAINT fk_transito_condicion_especial FOREIGN KEY (id_condicion_especial) REFERENCES condiciones_especiales(id);

ALTER TABLE formulario_transito_condiciones
    ADD CONSTRAINT fk_transito_condicion_formulario FOREIGN KEY (id_formulario_transito) REFERENCES formulario_hogar_transito(id);

ALTER TABLE movimientos
    ADD CONSTRAINT fk_movimiento_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id);

ALTER TABLE movimientos
    ADD CONSTRAINT fk_movimiento_tipo FOREIGN KEY (id_tipo_movimiento) REFERENCES tipos_movimientos(id);

ALTER TABLE movimientos
    ADD CONSTRAINT fk_movimiento_aporte FOREIGN KEY (id_tipo_aporte) REFERENCES tipos_aportes(id);

ALTER TABLE movimientos
    ADD CONSTRAINT fk_movimiento_metodo_pago FOREIGN KEY (id_metodo_pago) REFERENCES metodos_pago(id);

ALTER TABLE movimientos
    ADD CONSTRAINT fk_movimiento_frecuencia FOREIGN KEY (id_frecuencia_aporte) REFERENCES frecuencia_aportes(id);

ALTER TABLE auditorias
    ADD CONSTRAINT fk_auditoria_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id);

-- =====================================================
-- ÍNDICES
-- =====================================================
CREATE UNIQUE INDEX uq_contacto_principal_activo
    ON contactos (id_usuario, id_tipo_contacto)
    WHERE es_principal = TRUE AND estado = TRUE;
